name: CI

# Controls when the action will run.
on:
  push:
    branches: [staging]
  pull_request:
    branches: [staging]

jobs:
  caprover-deploy:
    runs-on: ubuntu-latest
    container: node:14
    steps:
      - id: string
        uses: ASzc/change-string-case-action@v1
        with:
          string: ${{ github.repository }}
      - uses: voxmedia/github-action-slack-notify-build@v1
        id: slack # IMPORTANT: reference this step ID value in future Slack steps
        with:
          channel: _server-notifications
          status: STARTED
          color: warning
        env:
          SLACK_BOT_TOKEN: 'xoxb-420404516627-1954793560226-WMRrytdvgFcb0SJuMHA7d13W'

      - uses: actions/checkout@v2
        name: Checkout repository

      - uses: VaultVulp/gp-docker-action@1.1.8
        name: Build and Publish latest service image
        with:
          # Read note below to see how to generate the PAT
          github-token: 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
          image-name: ds-crawler-frontend
          image-tag: staging
          custom-args: --build-arg NEXT_PUBLIC_GRAPHQL_URI=https://ds-crawler-backend-staging.servers.hangar31.dev/graphql
      # DEPLOY TO CAPROVER. SECRETS STORED IN https://github.com/YOUR-USERNAME/deploy-to-caprover-using-github-actions/settings/secrets/actions
      - name: Deploy image
        uses: floms/action-caprover@v1
        with:
          host: 'https://captain.servers.hangar31.dev/'
          password: 'Lk6zYoeayyvAyuwHfAMwUFYm'
          app: 'ds-crawler-frontend-staging'
          image: 'docker.pkg.github.com/${{ steps.string.outputs.lowercase }}/ds-crawler-frontend:staging'

      - name: Notify slack success
        if: success()
        env:
          SLACK_BOT_TOKEN: 'xoxb-420404516627-1954793560226-WMRrytdvgFcb0SJuMHA7d13W'
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          message_id: ${{ steps.slack.outputs.message_id }}
          channel: _server-notifications
          status: SUCCESS
          color: good

      - name: Notify slack fail
        if: failure()
        env:
          SLACK_BOT_TOKEN: 'xoxb-420404516627-1954793560226-WMRrytdvgFcb0SJuMHA7d13W'
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          message_id: ${{ steps.slack.outputs.message_id }}
          channel: _server-notifications
          status: FAILED
          color: danger
